### ISSUE TITLE
External components are not used in ionic 2 components

### ISSUE THREAD

**Issue by thangam105** [conclurer/ionic2-systemjs#27]
Hi,
I have developed external components and I have install it by typing's file:./components.d.ts --global --save

I got compilation error when I use that component in ionic pages.
Need to change in anywhere in that project?

**Comment by marvinscharle** [comment]
If you use an external component (in the global namespace), you'll have to include it manually in index.html

**Comment by thangam105** [comment]
Thanks for reply,

1. I have added the components js file manually in index.html

<script src="/build/dependencies.js"></script>

<script src="/lib/js/jquery-2.1.4.min.js"></script>

<script src="/lib/js/ej.web.all.min.js"></script>

<script src="/lib/js/ej.angular2.js"></script>

2. I have used the third party components in ionic pages
import {Component} from '@angular/core';
import {CORE_DIRECTIVES, FORM_DIRECTIVES} from '@angular/common';
import {EJ_RADIOBUTTON_COMPONENTS} from 'ej/web.all';

@Component({
  templateUrl: './page1.html',
  directives: [EJ_RADIOBUTTON_COMPONENTS,CORE_DIRECTIVES]
})
export class Page1 {
  constructor() {

  }
}

3. Again i got compilation error 

D:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master>ionic serve

Running 'serve:before' gulp task before serve
[11:19:19] Starting 'clean'...
[11:19:19] Finished 'clean' after 116 ms
[11:19:19] Starting 'watch'...
[11:19:19] Starting 'sass'...
[11:19:19] Starting 'fonts'...
[11:19:19] Starting 'build-js'...
[11:19:19] Starting 'compile-tsc'...
[11:19:19] Finished 'build-js' after 40 ms
[11:19:40] Finished 'sass' after 21 s
[11:19:40] Finished 'compile-tsc' after 21 s
[11:19:40] Starting 'bundle-static'...
[11:19:40] Starting 'systemjs-build-vendor'...
[11:19:41] Starting 'bundle-app'...
[11:19:41] Finished 'fonts' after 22 s
[11:19:41] Finished 'watch' after 22 s
[11:19:41] Starting 'serve:before'...
[11:19:41] Finished 'serve:before' after 11 µs

[11:19:41] Finished 'bundle-static' after 1.33 s
[11:19:41] Finished 'bundle-app' after 626 ms
[11:19:42] 'systemjs-build-vendor' errored after 1.71 s
[11:19:42] Error on fetch for ej/web.all.js at file:///D:/thangam/Ionic app/ioni
c2-systemjs-master/ionic2-systemjs-master/node_modules/ej/web.all.js
        Loading app/dist/pages/page1/page1.js
        Loading app/dist/pages/tabs/tabs.js
        Loading app/dist/app.js
        Error: ENOENT: no such file or directory, open 'D:\thangam\Ionic app\ion
ic2-systemjs-master\ionic2-systemjs-master\node_modules\ej\web.all.js'
    at Error (native)
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $


Could you please help me ?

Regards,
Thangavel

**Comment by marvinscharle** [comment]
You might add a SystemJS map definition for your module. Check out https://github.com/systemjs/systemjs/blob/master/docs/config-api.md

**Comment by thangam105** [comment]
Hi,
 Thanks for reply...

1. I have added the SystemJS map
"map":{
        "ej/web.all":"./deps/js/ej.angular2.js"    
    }
2. Again i got compilation error.

 node --debug-brk=36412 --nolazy node_modules\gulp\bin\gulp.js systemjs-build-vendor 
Debugger listening on port 36412
[15:52:00] Using gulpfile d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\gulpfile.js
[15:52:00] Starting 'systemjs-build-vendor'...
[15:52:19] 'systemjs-build-vendor' errored after 19 s
[15:52:19] Error: Error on fetch for crypto.js at file:///d:/thangam/Ionic app/ionic2-systemjs-master/ionic2-systemjs-master/node_modules/crypto.js
	Loading app/dist/deps/js/reflect-metadata/Reflect.js
	ENOENT: no such file or directory, open 'd:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\crypto.js'
    at Error (native)
    at SystemJSNodeLoader.Builder.reset.loader.fetch (d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\builder.js:177:20)
    at d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:431:12
    at d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:423:8
    at d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:389:6
    at processImmediate [as _immediateCallback] (timers.js:383:17)
    at Trace.getLoadRecord (d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:132:4)
    at Trace.getAllLoadRecords (d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:590:15)

**Comment by thangam105** [comment]
1. I have used the  SystemJS Path.


 "paths": {
        "*": "./node_modules/*",
        "app/*": "app/*",
        "@angular/core": "./node_modules/@angular/core/index.js",
        "@angular/http": "./node_modules/@angular/http/index.js",
        "@angular/compiler": "./node_modules/@angular/compiler/index.js",
        "@angular/common": "./node_modules/@angular/common/index.js",
        "@angular/router": "./node_modules/@angular/router/index.js",
        "@angular/platform-browser": "./node_modules/@angular/platform-browser/index.js",
        "@angular/platform-browser-dynamic": "./node_modules/@angular/platform-browser-dynamic/index.js",
        "ionic-angular": "./node_modules/ionic-angular/index.js",
        "ionic-native": "./node_modules/ionic-native/dist/index.js",
        "ej/*":"./deps/js/ej.angular2.js"    
    },

2. Now i got compilation error  in crypto.js file
node --debug-brk=11781 --nolazy node_modules\gulp\bin\gulp.js systemjs-build-vendor 
Debugger listening on port 11781
[16:05:02] Using gulpfile d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\gulpfile.js
[16:05:02] Starting 'systemjs-build-vendor'...
[16:05:16] 'systemjs-build-vendor' errored after 13 s
[16:05:16] Error: Error on fetch for crypto.js at file:///d:/thangam/Ionic app/ionic2-systemjs-master/ionic2-systemjs-master/node_modules/crypto.js
	Loading app/dist/deps/js/reflect-metadata/Reflect.js
	ENOENT: no such file or directory, open 'd:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\crypto.js'
    at Error (native)
    at SystemJSNodeLoader.Builder.reset.loader.fetch (d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\builder.js:177:20)
    at d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:431:12
    at d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:423:8
    at d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:389:6
    at processImmediate [as _immediateCallback] (timers.js:383:17)
    at Trace.getLoadRecord (d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:132:4)
    at Trace.getAllLoadRecords (d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:590:15)
    at d:\thangam\Ionic app\ionic2-systemjs-master\ionic2-systemjs-master\node_modules\systemjs-builder\lib\trace.js:601:21

**Comment by thangam105** [comment]
Hi,

Thanks for reply,

1. Now i am not got compilation error by using SystemJS path and meta https://github.com/systemjs/builder/issues/304.
path:{
 "ej/*": "./ejAngular/js/ej.angular2.js"
},
"meta": {
        "ej/*": {
            "build": false
     }
2.  I am not able use the third party component in  ionic 2 component
  **page1.ts file**
@Component({
  templateUrl: './page1.html',
  directives:[EJ_TILE_COMPONENTS,CORE_DIRECTIVES]
})

  console error:  
EXCEPTION: Error: Uncaught (in promise): Unexpected directive value 'undefined' on the View of component 'Page1'


How to clear this issue?

Regards,
Thangavel E

**Comment by thangam105** [comment]
I have cleared my console error.
